import type {Metadata} from "next";
import Image from "next/image";
import {hasLocale} from "next-intl";
import {setRequestLocale} from "next-intl/server";
import {notFound} from "next/navigation";
import {SiteHeader} from "@/components/SiteHeader";
import {Link} from "@/i18n/navigation";
import {homeContent, products, ui} from "@/data/localized";
import {routing,type Locale} from "@/i18n/routing";
import {localizedPath,metadataFor} from "@/lib/seo";

const homePaths=Object.fromEntries(routing.locales.map(l=>[l,localizedPath(l,"home")])) as Record<Locale,string>;
export async function generateMetadata({params}:{params:Promise<{locale:string}>}):Promise<Metadata>{const {locale:l}=await params;if(!hasLocale(routing.locales,l))return{};const locale=l as Locale,c=homeContent[locale];return metadataFor(locale,{title:c.seoTitle,description:c.seoDescription,keywords:c.keywords,image:"/images/zodiac-gift-set-studio.png",paths:homePaths})}
export default async function Home({params}:{params:Promise<{locale:string}>}){const {locale:l}=await params;if(!hasLocale(routing.locales,l))notFound();const locale=l as Locale;setRequestLocale(locale);const c=homeContent[locale],t=ui[locale];const steps=[["01","Brief"],["02","Design"],["03","Sample"],["04","Production"]];return <main className="conceptPage rococo-v2"><SiteHeader locale={locale} paths={homePaths}/><section className="hero"><div className="heroCopy"><p className="eyebrow">{c.eyebrow}</p><h1>{c.title}</h1><p className="heroText">{c.lead}</p><div className="buttonRow"><Link className="button buttonPrimary" href="/inquiry" locale={locale}>{t.quote}</Link><Link className="button buttonGhost" href="/products" locale={locale}>{t.products}</Link></div></div><div className="heroVisual"><Image src="/images/zodiac-gift-set-studio.png" alt={products[0].translations[locale].imageAlts[0]} fill priority sizes="52vw"/></div></section><section className="categories section" id="products"><div className="sectionIntro"><p className="eyebrow">{t.categories.toUpperCase()}</p><h2>{c.categoryTitle}</h2><Link href="/products" locale={locale}>{t.products} →</Link></div><div className="categoryGrid">{products.map((p,index)=><article className={`category category${index+1}`} key={p.id}><span>{p.translations[locale].kicker}</span><h3>{p.translations[locale].name}</h3><p>{p.translations[locale].intro}</p><Link href={{pathname:"/products/[slug]",params:{slug:p.translations[locale].slug}}} locale={locale}>{t.products} →</Link></article>)}</div></section><section className="featured section"><div className="featuredImage"><Image src="/images/makeup-puff-gift-set-studio.png" alt={products[1].translations[locale].imageAlts[1]} fill sizes="55vw"/></div><div className="featuredCopy"><p className="eyebrow">OEM / ODM</p><h2>{c.featuredTitle}</h2><p>{c.featuredText}</p><Link href="/inquiry" locale={locale}>{t.quote} →</Link></div></section><section className="process section" id="oem"><div className="processHead"><p className="eyebrow">OEM / ODM</p><h2>{c.processTitle}</h2></div><div className="processGrid">{steps.map(([n,label])=><article key={n}><span>{n}</span><h3>{label}</h3></article>)}</div></section><section className="story section" id="story"><div className="founderPhoto"><Image src="/images/founder-yin-caixia.jpg" alt="Yin Caixia, Colotutu founder" fill sizes="38vw"/></div><div className="storyCopy"><p className="eyebrow">{t.story.toUpperCase()}</p><h2>{c.storyTitle}</h2><p>{c.storyText}</p><Link href="/contact" locale={locale}>{t.contact} →</Link></div></section></main>}
